# 해당 파일을 읽어 OAuth2ClientProperties 생성
# OAuth2ClientPropertiesRegistrationAdapter를 통해OAuth2ClientProperties에서 각 OAuth2 server마다 ClientRegistration 생성
# ClientRegistration 리스트를 InMemoryClientRegistrationRepository에 저장
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CILENT_ID}
            redirect-uri: http://localhost:3000/oauth/callback/kakao #TODO S3 연결후 바꿔야함
            client-authentication-method: POST
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize #인증을 요청하는 url을 작성
            token-uri: https://kauth.kakao.com/oauth/token #토큰을 요청하는 url
            user-info-uri: https://kapi.kakao.com/v2/user/me #회원 정보를 가져오는 url
            user-name-attribute: id


Kakaopay:
    KakaoAK: ${KAKAO_AUTH_ORDER_KEY}




