spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
  jpa:
    hibernate:
#      hb2ddl.auto: validate
      ddl-auto: create-drop  # ?? ? ????!!!
    show-sql: true      # ??????
    properties:
      hibernate:
        format_sql: true # ??? ????
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

#postman ???? ??? ??? ?? ???.
server:
  servlet:
    encoding:
      force-response: true
      charset: utf-8
      force: true
